### ISSUE TITLE
一直回复 问题太难了， 出错了，报上下文太长的错误

### ISSUE THREAD

**Issue by w245607930** [WenHowe/feishu-chatgpt-express#1]

**Comment by w245607930** [comment]
discardConversation这个方法里面查询有问题
db.get(`SELECT id, msgSize FROM ${MsgTable} WHERE session_id = ?`, [sessionId], (err, data) => {
应该改成 db.all(`SELECT id, msgSize FROM ${MsgTable} WHERE session_id = ?`, [sessionId], (err, data) => {

**Comment by WhyMeta** [comment]
> 

确实，因为使用db.get只会返回一条结果，而且没有结果时会undefined，如果db.all，即使没有结果也可以返回空数组，在.length里为0，也可以多加个判断.length非0时在处理业务
